TIMELINE_PAGE = 0
ADD_APP_REQUEST_PAGE = 1
USERS_PAGE = 2
PROFILE_PAGE = 3
PROJECT_PAGE = 4
ADD_SUBMISSION_PAGE = 5
SUBMISSION_PAGE = 6
PROJECTS_PAGE = 7
ADD_REVIEW_PAGE = 8
REVIEW_PAGE = 9

LEFT_MENU_APPREQUEST_TYPE = 0
LEFT_MENU_SUBMISSION_TYPE = 1
LEFT_MENU_REVIEW_TYPE = 2

BUTTON_TYPE_NORMAL = 0
BUTTON_TYPE_CONFIRM = 1
